# Generated by Django 5.0 on 2024-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_photo_alter_house_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
