# Generated by Django 5.0 on 2024-01-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_photo_alter_house_date'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odrer',
            new_name='Order',
        ),
    ]
